# Generated by Django 3.2 on 2021-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_type', models.CharField(choices=[[1, 'ONE'], [2, 'TWO']], default='ONE', max_length=30)),
                ('rarity', models.CharField(choices=[[0, 'RARE'], [1, 'NOT RARE']], default='NOT RARE', max_length=30)),
                ('on_sale', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
