# Generated by Django 3.2.5 on 2021-07-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[['Player', 'PLAYER'], ['Manager', 'MANAGER'], ['Team', 'TEAM']], default='ONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[['0', 'BASIC'], ['1', 'RARE'], ['2', 'LEGEND']], default='NOT RARE', max_length=30),
        ),
    ]
