# Generated by Django 3.2.5 on 2021-07-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0002_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[['1', 'ONE'], ['2', 'TWO']], default='ONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[['0', 'RARE'], ['1', 'NOT RARE']], default='NOT RARE', max_length=30),
        ),
    ]
