# Generated by Django 3.2.5 on 2021-08-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0003_auto_20210804_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
