# Generated by Django 3.2.5 on 2021-07-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_UserApp_customuser_friends_+', to='UserApp.CustomUser'),
        ),
    ]
