# Generated by Django 3.2.5 on 2021-07-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='images/_7XI8ec0_400x400.jpg', null=True, upload_to='images/'),
        ),
    ]
