# Generated by Django 3.1.7 on 2021-08-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20210802_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, default='images/ProfilePicture.png', null=True, upload_to='images/'),
        ),
    ]
