# Generated by Django 3.2.5 on 2021-07-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_UserApp_customuser_friends_+', to='UserApp.CustomUser'),
        ),
    ]
