# Generated by Django 3.1.7 on 2021-08-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_customuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
    ]
